// SPDX-License-Identifier: MIT
pragma solidity ^0.8.21;

import {Script} from 'lib/forge-std/src/Script.sol';
import {console} from 'forge-std/console.sol';
import {BalanceContainerRootVerifier} from '../src/BalanceContainerRootVerifier.sol';
import {stdJson} from 'forge-std/StdJson.sol';

/**
 * @title TestBalanceContainerRootVerifier
 * @notice Script to test balance verification using data generated by metalayerProofGenerator.js
 * @dev This demonstrates the complete flow from beacon state to on-chain verification
 */
contract TestBalanceContainerRootVerifier is Script {
    using stdJson for string;

    // Structure to hold the parsed JSON data
    struct VerificationData {
        bytes32 balanceContainerRoot;
        bytes32[] balanceContainerProof;
        uint256 validatorIndex;
        uint256 leafIndex;
        bytes32 packedBalances;
        bytes32[] balanceProof;
        uint256 currentBalance;
        bytes32 beaconBlockRoot;
        uint256 slot;
        uint256 timestamp;
    }

    function run() external {
        // Configuration
        address verifierAddress = address(0x5FbDB2315678afecb367f032d93F642f64180aa3); // Your deployed address

        console.log('Testing Balance Verification with Metalayer-generated data');
        console.log('============================================================');

        // Load the verifier contract
        BalanceContainerRootVerifier verifier = BalanceContainerRootVerifier(verifierAddress);

        // Load and parse JSON data
        string memory root = vm.projectRoot();
        string memory path = string.concat(root, '/script/balanceVerification_test.json');
        string memory json = vm.readFile(path);

        console.log('Loading data from:', path);

        // Parse the verification data
        VerificationData memory data = _parseVerificationData(json);

        // Run the test with parsed data
        _runTestWithParsedData(verifier, data);
    }

    function _parseVerificationData(string memory json) internal returns (VerificationData memory) {
        VerificationData memory data;

        // Parse simple fields
        data.balanceContainerRoot = json.readBytes32('.balanceContainerRoot');
        data.validatorIndex = json.readUint('.validatorIndex');
        data.leafIndex = json.readUint('.leafIndex');
        data.packedBalances = json.readBytes32('.packedBalances');
        data.currentBalance = json.readUint('.currentBalance');
        data.beaconBlockRoot = json.readBytes32('.beaconBlockRoot');
        data.slot = json.readUint('.slot');
        data.timestamp = json.readUint('.timestamp');

        // Parse balance proof array
        bytes32[] memory balanceProofTemp = abi.decode(json.parseRaw('.balanceProof'), (bytes32[]));
        data.balanceProof = balanceProofTemp;

        // Parse balance container proof array
        bytes32[] memory containerProofTemp = abi.decode(json.parseRaw('.balanceContainerProof'), (bytes32[]));
        data.balanceContainerProof = containerProofTemp;

        return data;
    }

    function _runTestWithParsedData(BalanceContainerRootVerifier verifier, VerificationData memory data) internal {
        console.log('\n1. Test Data Summary:');
        console.log('====================');
        console.log('   Slot:', data.slot);
        console.log('   Timestamp:', data.timestamp);
        console.log('   Validator Index:', data.validatorIndex);
        console.log('   Leaf Index:', data.leafIndex);
        console.log('   Current Balance (gwei):', data.currentBalance);
        console.log('   Beacon Block Root:', vm.toString(data.beaconBlockRoot));
        console.log('   Balance Container Root:', vm.toString(data.balanceContainerRoot));
        console.log('   Packed Balances:', vm.toString(data.packedBalances));

        console.log('\n2. Testing balance verification...');

        vm.startBroadcast();

        // Call verifyBalance with the parsed data
        bool isValid = verifier.verifyBalance(
            data.balanceProof,
            data.packedBalances,
            data.balanceContainerRoot,
            data.leafIndex
        );

        console.log('Verification result:', isValid);

        if (!isValid) {
            console.log('   - Balance proof verification failed!');
            console.log('   - Proof length:', data.balanceProof.length);
            revert('Balance verification failed');
        }

        // Extract the individual balance from packed balances
        console.log('\n3. Testing balance extraction...');

        uint8 positionInLeaf = uint8(data.validatorIndex % 4);
        uint64 extractedBalance = verifier.extractBalance(data.packedBalances, positionInLeaf);

        console.log('   - Position in packed leaf:', positionInLeaf);
        console.log('   - Extracted Balance (gwei):', extractedBalance);
        console.log('   - Expected Balance (gwei):', data.currentBalance);

        bool balanceMatches = extractedBalance == uint64(data.currentBalance);
        console.log('   - Balance Match:', balanceMatches);

        // if (!balanceMatches) {
        //     console.log('   - WARNING: Extracted balance does not match expected!');
        //     console.log('   - Difference:', int256(extractedBalance) - int256(data.currentBalance));
        // }

        vm.stopBroadcast();

        // Summary
        console.log('\n4. Verification Summary');
        console.log('======================');
        if (isValid && balanceMatches) {
            console.log('All tests PASSED!');
            console.log('Successfully verified balance proof for validator', data.validatorIndex);
            console.log('at slot', data.slot, 'using Metalayer-generated data');
        } else if (isValid && !balanceMatches) {
            console.log('Proof verified but balance mismatch');
            console.log('This might indicate the validator index position calculation is off');
        } else {
            console.log('Verification FAILED');
            revert('Balance verification tests failed');
        }
    }


    /**
     * @notice Advanced test demonstrating batch verification
     * @dev This shows how to efficiently verify multiple validators
     */
    function testBatchVerification() external {
        console.log('\nBatch Balance Verification Test');
        console.log('===============================');

        BalanceContainerRootVerifier verifier = BalanceContainerRootVerifier(
            address(0x5FbDB2315678afecb367f032d93F642f64180aa3) // Update address
        );

        // Common data for all validators in this checkpoint
        bytes32 balanceContainerRoot = 0x1be49ab113dee06f8099491585b885330ea49fa5c34abb07841b7537bbda0541;

        // Validator batch data
        uint256[] memory validatorIndices = new uint256[](3);
        validatorIndices[0] = 10; // Leaf 2, position 2
        validatorIndices[1] = 11; // Leaf 2, position 3
        validatorIndices[2] = 100; // Leaf 25, position 0

        // Process each validator
        for (uint256 i = 0; i < validatorIndices.length; i++) {
            uint256 validatorIndex = validatorIndices[i];
            uint256 leafIndex = validatorIndex / 4;

            console.log('\nProcessing Validator', validatorIndex);
            console.log('  Leaf Index:', leafIndex);

            // Each validator might have different packed balances and proofs
            // In production, load these from the batch data

            // Note: Gas optimization opportunity
            // If multiple validators share the same leaf, we can reuse the proof
        }

        console.log('\nBatch verification complete');
    }
}
